language: R
sudo: required
cache: packages

before_install:
   - sudo apt-get install -y libhdf5-serial-dev

addons:
  apt:
    packages:
      - build-essential
      - hdf5-tools

notifications:
  email: philipp.muench@helmholtz-hzi.de
