language: r

dist: trusty
sudo: false

matrix:
  include:
    - name: "TensorFlow (Keras)"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
    - name: "Theano"
      env:
        - KERAS_BACKEND="theano"
        - THEANO_FLAGS=optimizer=fast_compile
    - name: "TensorFlow (TensorFlow)"
      env:
        - KERAS_BACKEND="tensorflow"
        - KERAS_IMPLEMENTATION="tensorflow"
    - name: "TensorFlow (TensorFlow 1.12)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_WHEEL="https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.12.0-cp27-none-linux_x86_64.whl"
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
    - name: "TensorFlow (TensorFlow 2.0-preview)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_WHEEL="https://files.pythonhosted.org/packages/ba/98/b0b9b83c9eddb9a112e0f928481c78232e1675397ccc717d1dcd92b8544b/tf_nightly_2.0_preview-2.0.0.dev20190319-cp27-cp27mu-manylinux1_x86_64.whl"
  allow_failures:
    - name: "nightly"
      env:
        - TENSORFLOW_VERSION="nightly"
        - TENSORFLOW_PYTHON="/usr/bin/python3"
    - name: "TensorFlow (TensorFlow 2.0-preview)"
      env:
        - KERAS_IMPLEMENTATION="tensorflow"
        - TENSORFLOW_WHEEL="https://files.pythonhosted.org/packages/ba/98/b0b9b83c9eddb9a112e0f928481c78232e1675397ccc717d1dcd92b8544b/tf_nightly_2.0_preview-2.0.0.dev20190319-cp27-cp27mu-manylinux1_x86_64.whl"
        
cache:
  packages: true
  directories:
    - $HOME/.keras
    - $HOME/.cache/pip

before_script:
  - pip2.7 install --upgrade --ignore-installed --user travis virtualenv
  - pip2.7 install --upgrade --ignore-installed --user travis keras h5py pyyaml requests Pillow scipy theano
  - |
    if [[ ! -z "$TENSORFLOW_WHEEL" ]]; then
      pip2.7 install --upgrade --ignore-installed --user travis $TENSORFLOW_WHEEL
    else
      pip2.7 install --upgrade --ignore-installed --user travis tensorflow
      pip show tensorflow
    fi
