language: r
sudo: required
cache: packages
dist: trusty
warnings_are_errors: false

addons:
  apt:
    packages:
      - build-essential
      - libxml2-dev
      - autoconf
      - libtool
      - subversion
      - libmagick++-dev
env:
  global:
  - PKG_CFLAGS="-pedantic"
  - _R_CHECK_CRAN_INCOMING_=FALSE
  - ASAN="-fsanitize=address -fno-omit-frame-pointer"
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - CODECOV_TOKEN="e2914fef-6e65-4145-b931-03d31277099f"
  matrix:
  - HDF5_VERSION=1.10.1

matrix:
  exclude:
    - os: osx
  include:
    - os: osx
      env: HDF5_VERSION=1.10.1
  fast_finish: true

before_install:
  - chmod +x travis_setup.sh
  - ./travis_setup.sh
  - R -e "install.packages(c('hdf5r', 'devtools','pkgload', 'pkgdown', 'covr'))"

before_script:
  - R --no-save <<< 'pkgload::load_all(); devtools::document()'

after_success:
  - 'if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" != "cron" ]] ; then
    R --no-save <<< "devtools::install(); pkgdown::build_site()";
    git checkout master;
    export TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)";
    git config --global user.name "Travis CI";
    git config --global user.email "$COMMIT_AUTHOR_EMAIL";
    git config credential.helper "store --file=.git/credentials";
    echo "https://${GH_TOKEN}:@github.com" >> .git/credentials;
    git config push.default matching;
    git add --force man/*;
    git add --force README.md;
    git add --force docs/*;
    git rm -r --cached $(find . -type d -name "*_cache");
    git commit man DESCRIPTION NAMESPACE README.md docs -m "update auto-generated documentation [ci]" -m "$TRAVIS_COMMIT_MSG" || true;
    git push;
  fi;'
  - Rscript -e 'covr::codecov()'

notifications:
  email: philipp.muench@helmholtz-hzi.de
