# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libhdf5-dev
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install -y libcurl4-openssl-dev
language: R
sudo: true
cache: packages
