language: R
sudo: required
cache: packages

before_install:
   - sudo apt-get install -y sudo apt-get install libhdf5-dev

addons:
  apt:
    packages:
      - build-essential

notifications:
  email: philipp.muench@helmholtz-hzi.de
