#' generate states list for tSNE from a fasta folder
#' it is expected that the length of each fasta file is equal
#'
#' @param fasta.folder path to fasta folder
#' @param model.path path to model file
#' @param cell.numer number of cell to be extracted
#' @param flatten if ture, all cell number will be used
#' @export
generateStatesromFolder <- function(fasta.folder = "example_files/fasta",
                                    model.path = "example_files/dummy_model_cpu.hdf5"){
  files <- list.files(fasta.folder, full.names = T)
  states.list <- list()
  for (file in files) {
    message(paste("processing: ", file))
    states.list[[file]] <-  deepG::getStatesFromFasta(fasta.path = file, 
                                                      model.path = model.path,
                                                      verbose = F)
  }
  return(states.list)
}

#' run the tSNE on a cell from the states.list
#'
#' @param states.list list of states generated by generateStatesromFolder
#' @param cell.number number of cell/neuron that should go into tSNE
#' @param flatten if true, all cells will be used
#' @export
tsneFromStates <- function(states.list,
                           cell.number = 1,
                           flatten = FALSE){
  dim <- c(dim(data.frame(states.list[[1]]))[1],
           dim(data.frame(states.list[[1]]))[2],
           length(states.list))
  states.array <- array(as.numeric(unlist(states.list)),
                        dim = dim)
  if (flatten) {
    states <- t(do.call('rbind',lapply(1:dim(states.array)[3],
                                       function(x) cbind(states.array[x,,], t = x)))) # bring 3dim array to 2D
  } else {
    states <- t(states.array[,cell.number,])
  }
  tsne <- Rtsne::Rtsne(states, dims = 2, perplexity = 1 , verbose = TRUE, max_iter = 5000)
  return(tsne)
}

#' plot tSNE
#' 
#' @param tsne tsne from tsneFromStates (or Rtsne::Rtsne)
#' @export
plotTsne <- function(tsne){
  tsne_plot <- data.frame(x = tsne$Y[,1], y = tsne$Y[,2])
  p <- ggplot2::ggplot(tsne_plot, ggplot2::aes(x = x, y = y)) + ggplot2::geom_point()
  p <- p + ggplot2::theme_bw()
  return(p)
}
